### ISSUE TITLE
refac: ♻️ refactoring API

### ISSUE THREAD

**Issue by westhyun** [yeogiya/yeogiya-frontend#121]
### Task ✅

- [x] 이메일 중복 체크
- [x] 아이디 찾기
- [x] 아이디 중복 체크
- [x] 닉네임 중복 체크
- [x] 비밀번호 재설정 이메일 발송

### Memo 🚨

- PP-214
