### ISSUE TITLE
style: 💄 아이디 찾기 페이지 UI

### ISSUE THREAD

**Issue by changedan** [yeogiya/yeogiya-frontend#19]
### Task ✅

- [x] UI - 아이디 찾기_공통 컴포넌트 사용(text, email, button)
- [x] UI - 버튼(이메일로찾기/비밀번호 찾으러 가기/뒤로가기)
- [x] UI - 아이디 찾기 결과 masking

### Memo 🚨

- PP-47
