### ISSUE TITLE
style: 💄 validation UI 수정

### ISSUE THREAD

**Issue by westhyun** [yeogiya/yeogiya-frontend#44]
### Task ✅
- [x] validation, style 수정
- [x] 로그인 페이지 router 설정
- [x] 비밀번호 찾기 페이지 UI 수정
- [x] 아이디찾기 페이지 UI 수정

### Memo 🚨

PP-140
