### ISSUE TITLE
style: 💄 공간일기쓰기 작성 페이지 UI

### ISSUE THREAD

**Issue by westhyun** [yeogiya/yeogiya-frontend#45]
### Task ✅

- [x] 공통 컴포넌트 - 토글 버튼 🚧
- [x] 공통 컴포넌트 - datepicker
- [x] 공통 컴포넌트 - 사진 업로드
- [x] 공통 컴포넌트 - 본문 text
- [x] 공통 컴포넌트 - tag

### Memo 🚨

PP-129
