### ISSUE TITLE
style: 💄 지도 페이지 UI

### ISSUE THREAD

**Issue by westhyun** [yeogiya/yeogiya-frontend#51]
### Task ✅
- [x] 지도 페이지 - header
- [x] 지도 페이지 레이아웃
- [x] 지도 페이지 UI
- [x]  navbar UI 수정

### Memo 🚨

- PP-125
