### ISSUE TITLE
fix: 🐛 회원정보조회, 공간일기작성 error & UI

### ISSUE THREAD

**Issue by westhyun** [yeogiya/yeogiya-frontend#97]
### Task ✅

- [x] favicon 추가
- [x] diary create page - 해시태그 UI 수정
- [x] tanstack-query 회원정보조회 API 에러 수정
- [x] diary create page - error fix

### Memo 🚨

- PP-195
